services:
  api:
    build:
      dockerfile: ./api/Dockerfile
      args:
        API_PORT: ${API_PORT}
    environment:
      API_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    develop:
      watch:
        - action: sync
          path: ./api/app
          target: /code/app
        - action: rebuild
          path: ./api/requirements.txt
          target: /code
    volumes:
      - ./api/alembic:/code/alembic
      - ./api/app:/code/app
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      args:
        FRONTEND_PORT: ${FRONTEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}