services:
  api:
    env_file:
      - .env
    build:
      dockerfile: ./api/Dockerfile
      args:
        API_PORT: ${API_PORT}
    environment:
      API_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    develop:
      watch:
        - action: sync
          path: ./api/app
          target: /api/app
        - action: rebuild
          path: ./api/requirements.txt
          target: /api
    volumes:
      - ./api/migrations:/api/migrations
      - ./api/app/data:/api/app/data
  frontend:
    env_file:
      - .env
    build:
      dockerfile: ./frontend/Dockerfile
      args:
        FRONTEND_PORT: ${FRONTEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}